
@host = http://localhost:5000


GET {{host}} HTTP/1.1
User-Agent: vscode-restclient
Accept-Encoding: gzip, deflate


###
GET {{host}}/datetime HTTP/1.1
User-Agent: vscode-restclient
Accept-Encoding: gzip, deflate


###
GET {{host}}/version HTTP/1.1
User-Agent: vscode-restclient
Accept-Encoding: gzip, deflate

###

GET {{host}}/hello HTTP/1.1
User-Agent: vscode-restclient
Accept-Encoding: gzip, deflate